cryptotest/tests/AlgorithmParametersTests.java, cryptotest/tests/CipherTests.java, cryptotest/tests/KeyAgreementTests.java, cryptotest/tests/KeyFactoryTests.java, cryptotest/tests/KeyPairGeneratorTests.java, cryptotest/tests/SignatureTests.java
There are new curves, that need different parameters or specs, so it was fake failing.
Only three tests keep failing, I am still investigating why.
=> Fixed failing cryptotests for OpenJDK 11+

cryptotest/utils/AlgorithmTest.java
Unexpected exception during some algorithm testing should not kill the whole thing...
=> Handle generic exception from agorigm testing correctly

cryptotest/Settings.java, cryptotest/tests/CertPathBuilderTests.java, cryptotest/tests/CipherTests.java, cryptotest/tests/KeyFactoryTests.java, cryptotest/tests/KeyInfoFactoryTests.java, cryptotest/tests/MacTests.java, cryptotest/tests/SignatureTests.java, cryptotest/utils/KeysNaiveGenerator.java
This PR does some fixes for FIPS mode:
- we can not use "RAW" keys (so generators are used)
- fixed block size detection in CipherTests
Testsuites fixed: SignatureTests, CipherTests, CertPathBuilderTests, MacTests
more to be done...
=> FIPS fixes: key generation, block size fixes

Makefile
Command itself is not printed for list-tests Makefile target.
=> Command not printed for list-tests target

cryptotest/tests/SecretKeyFactoryTests.java
KeyGenerators not used for PBE, PBKDF2 algorithms for SunPKCS11-NSS-FIPS provider. There may be additional changes later based on JIRA issue. See discussion in:
https://issues.redhat.com/browse/OPENJDK-991
=> SecretKeyFactoryTests: KeyGenerators are not used for PBE algorithms in FIPS

cryptotest/tests/SignatureTests.java
Skipped SHA3 signatures for SunPKCS11-NSS-FIPS provider as they are not provided by underlying NSS. See:
https://issues.redhat.com/browse/OPENJDK-826
=> SignatureTests: skip SHA3 signatures for pkcs11 fips

cryptotest/tests/SignatureTests.java
I realized previous pattern also matched SHA384, fixed.
e.g.:
we want to match:
SHA3-384withRSA
but not:
SHA384withRSA
=> SignatureTests: improved pattern matching SHA3

cryptotest/tests/KeyFactoryTests.java, cryptotest/utils/Misc.java
In FIPS mode there are some additional KeyFactories from non-fips providers, used internally (do not have KeyGenerators available), so skipped. (testing of KeyFactories from non-fips providers is skipped if configuration has FIPS provider)
See Martin's comment in this JIRA issue:
https://issues.redhat.com/browse/OPENJDK-827
=> KeyFactoryTests: skip KeyFactories from other providers in FIPS mode

cryptotest/tests/KeyStoreTests.java
In case of PKCS11 provider password is actually interpreted as pin to PKCS11 token. (pin is empty string in default configuration) Seems like password was previously ignored for PKCS11 keystore, but that has changed in:
https://github.com/rh-openjdk/jdk/pull/17/commits
=> KeyStoreTests: use empty pin for pkcs11 keystore

cryptotest/tests/SecretKeyFactoryTests.java
Fixes for PBE and PBKDF2 algorithms in FIPS mode. For more details see disussion in this JIRA:
https://issues.redhat.com/projects/OPENJDK/issues/OPENJDK-991
=> SecretKeyFactoryTests: PBE and PBKDF2 algorithms fixed in FIPS

cryptotest/tests/CipherTests.java
**Problem:**
JDK19 currently has failures such as:
```
java.lang.Exception: 11)	SunJCE: 	AES_128/KW/NoPadding~AES_128/KW/NoPadding	 (Cipher)
at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:83)
at cryptotest.tests.CipherTests.main(CipherTests.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: cryptotest.utils.AlgorithmRunException: javax.crypto.IllegalBlockSizeException: data should be at least 16 bytes and multiples of 8
at cryptotest.tests.CipherTests.checkAlgorithm(CipherTests.java:123)
at …
```
=> CipherTests: Fixed KW ciphers

cryptotest/tests/TerminalFactoryTests.java
Non-ascii characters are causing problems in some environments :(
https://github.com/adoptium/aqa-tests/issues/4335
=> Fix TerminalFactoryTests to use ASCII only characters

.github/workflows/test.yaml, .gitignore, run.sh
Added testing using jtreg in GitHub CI.
Changes:
- added jobs to GH workflow file to also perform testing using run.sh (using jtreg)
- switched to older jtreg version, jtreg-7+1 does not work with JDK 8
- updated run.sh to end with non-zero on failures/errors
- added possibility to skip agent test when running using run.sh (using env. variable named same as in Makefile)
- updated .gitignore to not accidentally commit files generated by run.sh/jtreg
=> Enabled testing using jtreg in GitHub CI

cryptotest/CryptoTest.java, cryptotest/tests/GssApiMechanismTests.java, cryptotest/tests/KeyFactoryTests.java, cryptotest/tests/SaslServerFactoryTests.java, cryptotest/tests/SecretKeyFactoryTests.java, cryptotest/tests/SignatureTests.java, cryptotest/utils/AlgorithmIgnoredException.java, cryptotest/utils/AlgorithmTest.java
This allows to explicitly ignore algorithm by throwing `AlgorithmIgnoredException`. This will not cause failure, but it can be seen which algorithms were ignored by inspecting logs.
Currently only difference from `passed` is that it shows as `ignored` in logs. See agent tests in GH CI:
https://github.com/zzambers/CryptoTest/actions/runs/4184556466/jobs/7250364921#step:5:758
https://github.com/zzambers/CryptoTest/actions/runs/4184556466/jobs/7250364921#step:5:807
(other ignores only shows for rpms in FIPS mode)
=> Added support for explicitly ignoring algorithms

cryptotest/tests/KeyStoreTests.java, cryptotest/utils/Misc.java
Problem:
SunMSCAPI `*-LOCALMACHINE` keystores (Windows) require admin privileges.
```
java.lang.Exception: 6)	SunMSCAPI: 	Windows-ROOT-LOCALMACHINE~Windows-ROOT-LOCALMACHINE	 (KeyStore)
at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:83)
at cryptotest.tests.KeyStoreTests.main(KeyStoreTests.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
at java.base/java.lang.Thread.run(Thread.java:829) …
```
=> KeyStoreTests: fixed SunMSCAPI keystores

.github/workflows/test.yaml, Makefile
Added Windows testing in GitHub
=> Added Windows testing in GitHub

.github/workflows/test.yaml
With recently added test configurations, GH workflow file started to become little bloated. This change switches to matrix configuration to reduce duplicity and improve readability/maintainability.
=> Use matrix configurations in GH workflow file

.github/workflows/test.yaml
Updated version of checkout action in GitHub workflow as v2 produces [warnings](https://github.com/rh-openjdk/CryptoTest/actions/runs/4281283694):
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
=> Updated version of checkout action in GH workflow

.github/workflows/test.yaml
Enabled testing on latest available Temurin (JDK19), so that we could catch here issues on newer jdks, such as: https://github.com/rh-openjdk/CryptoTest/pull/31
=> Added GitHub testing with JDK19

cryptotest/tests/SignatureTests.java
Increased timeout for SignatureTests. There has been reports of timeouts on some platforms, based on stack trace, test is not stuck on blocking call (such as reading from /dev/random), but is doing some BigInteger arithmetic (BigInteger arithmetic being slow on some platforms?). See:
https://github.com/adoptium/aqa-tests/issues/4336#issuecomment-1512952403
=> Increased timeout for SignatureTests

cryptotest/tests/GssApiMechanismTests.java, cryptotest/tests/SaslServerFactoryTests.java, cryptotest/utils/Misc.java
Explicitly fail tests, requiring agent, when agent hostname is not configured. (Unless they are skipped)
=> Explicitly fail agent tests when agent hostname is not configured

cryptotest/tests/CertPathBuilderTests.java, cryptotest/tests/CertPathValidatorTests.java
Try with resources is used for keystore input stream as done in [javadoc](https://docs.oracle.com/javase/8/docs/api/java/security/KeyStore.html).
=> Make sure InputStream is closed after loading keystore

cryptotest/tests/AlgorithmParametersTests.java, cryptotest/tests/CertStoreTests.java, cryptotest/tests/CertificateFactoryTests.java, cryptotest/tests/CipherTests.java, cryptotest/tests/GssApiMechanismTests.java, cryptotest/tests/KeyGeneratorTests.java, cryptotest/tests/KeyStoreTests.java, cryptotest/tests/MacTests.java, cryptotest/tests/MessageDigestTests.java, cryptotest/tests/SecureRandomTests.java, cryptotest/tests/SignatureTests.java, cryptotest/tests/TransformServiceTests.java
I believe that `IwishThisCouldBeAtTest` comment refers to using `@test` jtreg tag for `*Tests` classes, which is already done.
=> Remove obsolete comments from tests classes

cryptotest/tests/KeyFactoryTests.java, cryptotest/tests/SignatureTests.java
Support for HSS/LMS signatures was added by [JDK-8298127](https://bugs.openjdk.org/browse/JDK-8298127). However signing is not supported (only signature verification) and there are no key generators. Ignored for now. (Seems this would need more compicated setup, where keys/certificates would be generated by 3rd party software and supplied by test... :/ )
=> Fix HSS/LMS failures on jdk21

.github/workflows/test.yaml
Updated GH testing to use 21 as latest.
=> GH testing uses jdk 21 as latest

cryptotest/CryptoTest.java
- Increased the timeout to 1800
related: https://github.com/eclipse-openj9/openj9/issues/19264
Signed-off-by: Anna Babu Palathingal <anna.bp@ibm.com>
=> Increase timeout for cryptotest/CryptoTest test

.github/workflows/test.yaml
Updates upload-artifact action to v4, as v3 no longer works and [breaks](https://github.com/zzambers/CryptoTest/actions/runs/13790230254/job/38567912867) testing with:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
**Additional changes:**
Artifact name is now explicitly specified. Previously default name `artifact` was used, but that no longer works, because upload-artifact v4 [no longer allows](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) uploading to same named artifact more than once (appending).
=> Update upload-artifact to v4

cryptotest/CryptoTest.java, cryptotest/tests/KDFTests.java
This adds support for testing of KDF API. (see [JDK-8331008](https://bugs.openjdk.org/browse/JDK-8331008).
Fixes: https://github.com/rh-openjdk/CryptoTest/issues/72
Currently reflection has to be, so that tests support all jdks... :(
(I have included comment with original code, without reflection)
=> Add KDFTests

cryptotest/tests/KEMTests.java
Just adding comment (similar to one in KDFTests) also to KEMTests + some cosmetic changes.
=> KEMTests: comment and cosmetic changes
